### ISSUE TITLE
Ability to change Pytri fibers linewidth

### ISSUE THREAD

**Issue by ndrenkow** [aplbrain/pytri#104]
I would like to have the option when I call p.fibers() to change the linewidth.  Thanks!

**Comment by j6k4m8** [comment]
Thank you for posting!

This is something we've been working on for a while; it turns out that there's a WebGL [implementation-level rendering issue](https://www.khronos.org/registry/OpenGL/specs/gl/glspec46.core.pdf) that restricts line width; we're looking at a view options in order to fix this in [substrate](https://github.com/iscoe/substrate). This is definitely on our radar!

**Comment by j6k4m8** [comment]
Planning to re-implement this as [billboarded triangles.](https://github.com/spite/THREE.MeshLine)

**Comment by j6k4m8** [comment]
This is fixed in the latest version with `Figure#lines` (#111)

You can pass a single `width` argument (in scene-units):

```python
fig = Figure()
fig.lines(..., width=100)
```

Because this happens at the shader-level, multiple `lines`s are needed to make multiple widths.
