### ISSUE TITLE
Figure module not found

### ISSUE THREAD

**Issue by vinuvargheseijk** [aplbrain/pytri#121]
I am using python3

In [13]: from pytri import Figure

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-13-cc2bd170c146> in <module>()
----> 1 from pytri import Figure

ImportError: cannot import name 'Figure'

**Comment by j6k4m8** [comment]
Hi @vinuvargheseijk! Thanks for reporting. Can you share which version of Pytri you're using?

```shell
pip3 freeze | grep pytri
```

**Comment by vinuvargheseijk** [comment]
pytri==0.5.0

**Comment by j6k4m8** [comment]
Thank you @vinuvargheseijk! This was my fault; I hadn't pushed the latest version to pypi. You should be able to update now with:

```shell
pip3 install -U pytri
```

The current latest version is 2.0.1:

```python3
>>> import pytri
>>> pytri.__version__
'2.0.1'
```

Or:

```shell
pip3 freeze | grep pytri # (should also show 2.0.1)
```

Let me know if that fixes the issue? (There have also been some great performance improvements since v0.5 so I'm glad we can make the change!)

**Comment by vinuvargheseijk** [comment]
Thanks @j6k4m8 . Works now

pytri==2.0.1

In [1]: from pytri import Figure

In [2]: f=Figure()

**Comment by j6k4m8** [comment]
Awesome @vinuvargheseijk :) Let me know if you run into any other issues!
